version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
    ports:
      - "3306:3306"
    command: --bind-address=0.0.0.0

  forum-backend:
    build: .
    depends_on:
      - mysql
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - backend

volumes:
  mysql-data:

networks:
  backend:
    driver: bridge
