version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
    ports:
      - "3306:3306"
    command: --bind-address=0.0.0.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent", "--password=${MYSQL_ROOT_PASSWORD}"]
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 10s

  forum-backend:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - backend
    restart: on-failure

volumes:
  mysql-data:

networks:
  backend:
    driver: bridge